/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const DashboardRouteLazyRouteImport = createFileRoute('/dashboard')()
const IndexLazyRouteImport = createFileRoute('/')()
const DashboardIndexLazyRouteImport = createFileRoute('/dashboard/')()
const DashboardServersLazyRouteImport = createFileRoute('/dashboard/servers')()
const DashboardPluginLazyRouteImport = createFileRoute('/dashboard/plugin')()
const DashboardNodesLazyRouteImport = createFileRoute('/dashboard/nodes')()
const DashboardUserIndexLazyRouteImport = createFileRoute('/dashboard/user/')()
const DashboardTicketIndexLazyRouteImport =
  createFileRoute('/dashboard/ticket/')()
const DashboardSystemIndexLazyRouteImport =
  createFileRoute('/dashboard/system/')()
const DashboardSubscribeIndexLazyRouteImport = createFileRoute(
  '/dashboard/subscribe/',
)()
const DashboardProductIndexLazyRouteImport = createFileRoute(
  '/dashboard/product/',
)()
const DashboardPaymentIndexLazyRouteImport = createFileRoute(
  '/dashboard/payment/',
)()
const DashboardOrderIndexLazyRouteImport =
  createFileRoute('/dashboard/order/')()
const DashboardMarketingIndexLazyRouteImport = createFileRoute(
  '/dashboard/marketing/',
)()
const DashboardDocumentIndexLazyRouteImport = createFileRoute(
  '/dashboard/document/',
)()
const DashboardCouponIndexLazyRouteImport =
  createFileRoute('/dashboard/coupon/')()
const DashboardAuthControlIndexLazyRouteImport = createFileRoute(
  '/dashboard/auth-control/',
)()
const DashboardAnnouncementIndexLazyRouteImport = createFileRoute(
  '/dashboard/announcement/',
)()
const DashboardAdsIndexLazyRouteImport = createFileRoute('/dashboard/ads/')()
const DashboardLogTrafficDetailsLazyRouteImport = createFileRoute(
  '/dashboard/log/traffic-details',
)()
const DashboardLogSubscribeTrafficLazyRouteImport = createFileRoute(
  '/dashboard/log/subscribe-traffic',
)()
const DashboardLogSubscribeLazyRouteImport = createFileRoute(
  '/dashboard/log/subscribe',
)()
const DashboardLogServerTrafficLazyRouteImport = createFileRoute(
  '/dashboard/log/server-traffic',
)()
const DashboardLogResetSubscribeLazyRouteImport = createFileRoute(
  '/dashboard/log/reset-subscribe',
)()
const DashboardLogRegisterLazyRouteImport = createFileRoute(
  '/dashboard/log/register',
)()
const DashboardLogMobileLazyRouteImport = createFileRoute(
  '/dashboard/log/mobile',
)()
const DashboardLogLoginLazyRouteImport = createFileRoute(
  '/dashboard/log/login',
)()
const DashboardLogGiftLazyRouteImport = createFileRoute('/dashboard/log/gift')()
const DashboardLogEmailLazyRouteImport = createFileRoute(
  '/dashboard/log/email',
)()
const DashboardLogCommissionLazyRouteImport = createFileRoute(
  '/dashboard/log/commission',
)()
const DashboardLogBalanceLazyRouteImport = createFileRoute(
  '/dashboard/log/balance',
)()

const DashboardRouteLazyRoute = DashboardRouteLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/dashboard/route.lazy').then((d) => d.Route),
)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const DashboardIndexLazyRoute = DashboardIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)
const DashboardServersLazyRoute = DashboardServersLazyRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => DashboardRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/servers.lazy').then((d) => d.Route),
)
const DashboardPluginLazyRoute = DashboardPluginLazyRouteImport.update({
  id: '/plugin',
  path: '/plugin',
  getParentRoute: () => DashboardRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/plugin.lazy').then((d) => d.Route),
)
const DashboardNodesLazyRoute = DashboardNodesLazyRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => DashboardRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/nodes.lazy').then((d) => d.Route),
)
const DashboardUserIndexLazyRoute = DashboardUserIndexLazyRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => DashboardRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/user/index.lazy').then((d) => d.Route),
)
const DashboardTicketIndexLazyRoute =
  DashboardTicketIndexLazyRouteImport.update({
    id: '/ticket/',
    path: '/ticket/',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/ticket/index.lazy').then((d) => d.Route),
  )
const DashboardSystemIndexLazyRoute =
  DashboardSystemIndexLazyRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/system/index.lazy').then((d) => d.Route),
  )
const DashboardSubscribeIndexLazyRoute =
  DashboardSubscribeIndexLazyRouteImport.update({
    id: '/subscribe/',
    path: '/subscribe/',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/subscribe/index.lazy').then((d) => d.Route),
  )
const DashboardProductIndexLazyRoute =
  DashboardProductIndexLazyRouteImport.update({
    id: '/product/',
    path: '/product/',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/product/index.lazy').then((d) => d.Route),
  )
const DashboardPaymentIndexLazyRoute =
  DashboardPaymentIndexLazyRouteImport.update({
    id: '/payment/',
    path: '/payment/',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/payment/index.lazy').then((d) => d.Route),
  )
const DashboardOrderIndexLazyRoute = DashboardOrderIndexLazyRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => DashboardRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/order/index.lazy').then((d) => d.Route),
)
const DashboardMarketingIndexLazyRoute =
  DashboardMarketingIndexLazyRouteImport.update({
    id: '/marketing/',
    path: '/marketing/',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/marketing/index.lazy').then((d) => d.Route),
  )
const DashboardDocumentIndexLazyRoute =
  DashboardDocumentIndexLazyRouteImport.update({
    id: '/document/',
    path: '/document/',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/document/index.lazy').then((d) => d.Route),
  )
const DashboardCouponIndexLazyRoute =
  DashboardCouponIndexLazyRouteImport.update({
    id: '/coupon/',
    path: '/coupon/',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/coupon/index.lazy').then((d) => d.Route),
  )
const DashboardAuthControlIndexLazyRoute =
  DashboardAuthControlIndexLazyRouteImport.update({
    id: '/auth-control/',
    path: '/auth-control/',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/auth-control/index.lazy').then((d) => d.Route),
  )
const DashboardAnnouncementIndexLazyRoute =
  DashboardAnnouncementIndexLazyRouteImport.update({
    id: '/announcement/',
    path: '/announcement/',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/announcement/index.lazy').then((d) => d.Route),
  )
const DashboardAdsIndexLazyRoute = DashboardAdsIndexLazyRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => DashboardRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/ads/index.lazy').then((d) => d.Route),
)
const DashboardLogTrafficDetailsLazyRoute =
  DashboardLogTrafficDetailsLazyRouteImport.update({
    id: '/log/traffic-details',
    path: '/log/traffic-details',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/log/traffic-details.lazy').then((d) => d.Route),
  )
const DashboardLogSubscribeTrafficLazyRoute =
  DashboardLogSubscribeTrafficLazyRouteImport.update({
    id: '/log/subscribe-traffic',
    path: '/log/subscribe-traffic',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/log/subscribe-traffic.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardLogSubscribeLazyRoute =
  DashboardLogSubscribeLazyRouteImport.update({
    id: '/log/subscribe',
    path: '/log/subscribe',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/log/subscribe.lazy').then((d) => d.Route),
  )
const DashboardLogServerTrafficLazyRoute =
  DashboardLogServerTrafficLazyRouteImport.update({
    id: '/log/server-traffic',
    path: '/log/server-traffic',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/log/server-traffic.lazy').then((d) => d.Route),
  )
const DashboardLogResetSubscribeLazyRoute =
  DashboardLogResetSubscribeLazyRouteImport.update({
    id: '/log/reset-subscribe',
    path: '/log/reset-subscribe',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/log/reset-subscribe.lazy').then((d) => d.Route),
  )
const DashboardLogRegisterLazyRoute =
  DashboardLogRegisterLazyRouteImport.update({
    id: '/log/register',
    path: '/log/register',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/log/register.lazy').then((d) => d.Route),
  )
const DashboardLogMobileLazyRoute = DashboardLogMobileLazyRouteImport.update({
  id: '/log/mobile',
  path: '/log/mobile',
  getParentRoute: () => DashboardRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/log/mobile.lazy').then((d) => d.Route),
)
const DashboardLogLoginLazyRoute = DashboardLogLoginLazyRouteImport.update({
  id: '/log/login',
  path: '/log/login',
  getParentRoute: () => DashboardRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/log/login.lazy').then((d) => d.Route),
)
const DashboardLogGiftLazyRoute = DashboardLogGiftLazyRouteImport.update({
  id: '/log/gift',
  path: '/log/gift',
  getParentRoute: () => DashboardRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/log/gift.lazy').then((d) => d.Route),
)
const DashboardLogEmailLazyRoute = DashboardLogEmailLazyRouteImport.update({
  id: '/log/email',
  path: '/log/email',
  getParentRoute: () => DashboardRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/log/email.lazy').then((d) => d.Route),
)
const DashboardLogCommissionLazyRoute =
  DashboardLogCommissionLazyRouteImport.update({
    id: '/log/commission',
    path: '/log/commission',
    getParentRoute: () => DashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/log/commission.lazy').then((d) => d.Route),
  )
const DashboardLogBalanceLazyRoute = DashboardLogBalanceLazyRouteImport.update({
  id: '/log/balance',
  path: '/log/balance',
  getParentRoute: () => DashboardRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/log/balance.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardRouteLazyRouteWithChildren
  '/dashboard/nodes': typeof DashboardNodesLazyRoute
  '/dashboard/plugin': typeof DashboardPluginLazyRoute
  '/dashboard/servers': typeof DashboardServersLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/log/balance': typeof DashboardLogBalanceLazyRoute
  '/dashboard/log/commission': typeof DashboardLogCommissionLazyRoute
  '/dashboard/log/email': typeof DashboardLogEmailLazyRoute
  '/dashboard/log/gift': typeof DashboardLogGiftLazyRoute
  '/dashboard/log/login': typeof DashboardLogLoginLazyRoute
  '/dashboard/log/mobile': typeof DashboardLogMobileLazyRoute
  '/dashboard/log/register': typeof DashboardLogRegisterLazyRoute
  '/dashboard/log/reset-subscribe': typeof DashboardLogResetSubscribeLazyRoute
  '/dashboard/log/server-traffic': typeof DashboardLogServerTrafficLazyRoute
  '/dashboard/log/subscribe': typeof DashboardLogSubscribeLazyRoute
  '/dashboard/log/subscribe-traffic': typeof DashboardLogSubscribeTrafficLazyRoute
  '/dashboard/log/traffic-details': typeof DashboardLogTrafficDetailsLazyRoute
  '/dashboard/ads': typeof DashboardAdsIndexLazyRoute
  '/dashboard/announcement': typeof DashboardAnnouncementIndexLazyRoute
  '/dashboard/auth-control': typeof DashboardAuthControlIndexLazyRoute
  '/dashboard/coupon': typeof DashboardCouponIndexLazyRoute
  '/dashboard/document': typeof DashboardDocumentIndexLazyRoute
  '/dashboard/marketing': typeof DashboardMarketingIndexLazyRoute
  '/dashboard/order': typeof DashboardOrderIndexLazyRoute
  '/dashboard/payment': typeof DashboardPaymentIndexLazyRoute
  '/dashboard/product': typeof DashboardProductIndexLazyRoute
  '/dashboard/subscribe': typeof DashboardSubscribeIndexLazyRoute
  '/dashboard/system': typeof DashboardSystemIndexLazyRoute
  '/dashboard/ticket': typeof DashboardTicketIndexLazyRoute
  '/dashboard/user': typeof DashboardUserIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/dashboard/nodes': typeof DashboardNodesLazyRoute
  '/dashboard/plugin': typeof DashboardPluginLazyRoute
  '/dashboard/servers': typeof DashboardServersLazyRoute
  '/dashboard': typeof DashboardIndexLazyRoute
  '/dashboard/log/balance': typeof DashboardLogBalanceLazyRoute
  '/dashboard/log/commission': typeof DashboardLogCommissionLazyRoute
  '/dashboard/log/email': typeof DashboardLogEmailLazyRoute
  '/dashboard/log/gift': typeof DashboardLogGiftLazyRoute
  '/dashboard/log/login': typeof DashboardLogLoginLazyRoute
  '/dashboard/log/mobile': typeof DashboardLogMobileLazyRoute
  '/dashboard/log/register': typeof DashboardLogRegisterLazyRoute
  '/dashboard/log/reset-subscribe': typeof DashboardLogResetSubscribeLazyRoute
  '/dashboard/log/server-traffic': typeof DashboardLogServerTrafficLazyRoute
  '/dashboard/log/subscribe': typeof DashboardLogSubscribeLazyRoute
  '/dashboard/log/subscribe-traffic': typeof DashboardLogSubscribeTrafficLazyRoute
  '/dashboard/log/traffic-details': typeof DashboardLogTrafficDetailsLazyRoute
  '/dashboard/ads': typeof DashboardAdsIndexLazyRoute
  '/dashboard/announcement': typeof DashboardAnnouncementIndexLazyRoute
  '/dashboard/auth-control': typeof DashboardAuthControlIndexLazyRoute
  '/dashboard/coupon': typeof DashboardCouponIndexLazyRoute
  '/dashboard/document': typeof DashboardDocumentIndexLazyRoute
  '/dashboard/marketing': typeof DashboardMarketingIndexLazyRoute
  '/dashboard/order': typeof DashboardOrderIndexLazyRoute
  '/dashboard/payment': typeof DashboardPaymentIndexLazyRoute
  '/dashboard/product': typeof DashboardProductIndexLazyRoute
  '/dashboard/subscribe': typeof DashboardSubscribeIndexLazyRoute
  '/dashboard/system': typeof DashboardSystemIndexLazyRoute
  '/dashboard/ticket': typeof DashboardTicketIndexLazyRoute
  '/dashboard/user': typeof DashboardUserIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardRouteLazyRouteWithChildren
  '/dashboard/nodes': typeof DashboardNodesLazyRoute
  '/dashboard/plugin': typeof DashboardPluginLazyRoute
  '/dashboard/servers': typeof DashboardServersLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/log/balance': typeof DashboardLogBalanceLazyRoute
  '/dashboard/log/commission': typeof DashboardLogCommissionLazyRoute
  '/dashboard/log/email': typeof DashboardLogEmailLazyRoute
  '/dashboard/log/gift': typeof DashboardLogGiftLazyRoute
  '/dashboard/log/login': typeof DashboardLogLoginLazyRoute
  '/dashboard/log/mobile': typeof DashboardLogMobileLazyRoute
  '/dashboard/log/register': typeof DashboardLogRegisterLazyRoute
  '/dashboard/log/reset-subscribe': typeof DashboardLogResetSubscribeLazyRoute
  '/dashboard/log/server-traffic': typeof DashboardLogServerTrafficLazyRoute
  '/dashboard/log/subscribe': typeof DashboardLogSubscribeLazyRoute
  '/dashboard/log/subscribe-traffic': typeof DashboardLogSubscribeTrafficLazyRoute
  '/dashboard/log/traffic-details': typeof DashboardLogTrafficDetailsLazyRoute
  '/dashboard/ads/': typeof DashboardAdsIndexLazyRoute
  '/dashboard/announcement/': typeof DashboardAnnouncementIndexLazyRoute
  '/dashboard/auth-control/': typeof DashboardAuthControlIndexLazyRoute
  '/dashboard/coupon/': typeof DashboardCouponIndexLazyRoute
  '/dashboard/document/': typeof DashboardDocumentIndexLazyRoute
  '/dashboard/marketing/': typeof DashboardMarketingIndexLazyRoute
  '/dashboard/order/': typeof DashboardOrderIndexLazyRoute
  '/dashboard/payment/': typeof DashboardPaymentIndexLazyRoute
  '/dashboard/product/': typeof DashboardProductIndexLazyRoute
  '/dashboard/subscribe/': typeof DashboardSubscribeIndexLazyRoute
  '/dashboard/system/': typeof DashboardSystemIndexLazyRoute
  '/dashboard/ticket/': typeof DashboardTicketIndexLazyRoute
  '/dashboard/user/': typeof DashboardUserIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/nodes'
    | '/dashboard/plugin'
    | '/dashboard/servers'
    | '/dashboard/'
    | '/dashboard/log/balance'
    | '/dashboard/log/commission'
    | '/dashboard/log/email'
    | '/dashboard/log/gift'
    | '/dashboard/log/login'
    | '/dashboard/log/mobile'
    | '/dashboard/log/register'
    | '/dashboard/log/reset-subscribe'
    | '/dashboard/log/server-traffic'
    | '/dashboard/log/subscribe'
    | '/dashboard/log/subscribe-traffic'
    | '/dashboard/log/traffic-details'
    | '/dashboard/ads'
    | '/dashboard/announcement'
    | '/dashboard/auth-control'
    | '/dashboard/coupon'
    | '/dashboard/document'
    | '/dashboard/marketing'
    | '/dashboard/order'
    | '/dashboard/payment'
    | '/dashboard/product'
    | '/dashboard/subscribe'
    | '/dashboard/system'
    | '/dashboard/ticket'
    | '/dashboard/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/nodes'
    | '/dashboard/plugin'
    | '/dashboard/servers'
    | '/dashboard'
    | '/dashboard/log/balance'
    | '/dashboard/log/commission'
    | '/dashboard/log/email'
    | '/dashboard/log/gift'
    | '/dashboard/log/login'
    | '/dashboard/log/mobile'
    | '/dashboard/log/register'
    | '/dashboard/log/reset-subscribe'
    | '/dashboard/log/server-traffic'
    | '/dashboard/log/subscribe'
    | '/dashboard/log/subscribe-traffic'
    | '/dashboard/log/traffic-details'
    | '/dashboard/ads'
    | '/dashboard/announcement'
    | '/dashboard/auth-control'
    | '/dashboard/coupon'
    | '/dashboard/document'
    | '/dashboard/marketing'
    | '/dashboard/order'
    | '/dashboard/payment'
    | '/dashboard/product'
    | '/dashboard/subscribe'
    | '/dashboard/system'
    | '/dashboard/ticket'
    | '/dashboard/user'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/nodes'
    | '/dashboard/plugin'
    | '/dashboard/servers'
    | '/dashboard/'
    | '/dashboard/log/balance'
    | '/dashboard/log/commission'
    | '/dashboard/log/email'
    | '/dashboard/log/gift'
    | '/dashboard/log/login'
    | '/dashboard/log/mobile'
    | '/dashboard/log/register'
    | '/dashboard/log/reset-subscribe'
    | '/dashboard/log/server-traffic'
    | '/dashboard/log/subscribe'
    | '/dashboard/log/subscribe-traffic'
    | '/dashboard/log/traffic-details'
    | '/dashboard/ads/'
    | '/dashboard/announcement/'
    | '/dashboard/auth-control/'
    | '/dashboard/coupon/'
    | '/dashboard/document/'
    | '/dashboard/marketing/'
    | '/dashboard/order/'
    | '/dashboard/payment/'
    | '/dashboard/product/'
    | '/dashboard/subscribe/'
    | '/dashboard/system/'
    | '/dashboard/ticket/'
    | '/dashboard/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DashboardRouteLazyRoute: typeof DashboardRouteLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/servers': {
      id: '/dashboard/servers'
      path: '/servers'
      fullPath: '/dashboard/servers'
      preLoaderRoute: typeof DashboardServersLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/plugin': {
      id: '/dashboard/plugin'
      path: '/plugin'
      fullPath: '/dashboard/plugin'
      preLoaderRoute: typeof DashboardPluginLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/nodes': {
      id: '/dashboard/nodes'
      path: '/nodes'
      fullPath: '/dashboard/nodes'
      preLoaderRoute: typeof DashboardNodesLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/user/': {
      id: '/dashboard/user/'
      path: '/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof DashboardUserIndexLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/ticket/': {
      id: '/dashboard/ticket/'
      path: '/ticket'
      fullPath: '/dashboard/ticket'
      preLoaderRoute: typeof DashboardTicketIndexLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/system/': {
      id: '/dashboard/system/'
      path: '/system'
      fullPath: '/dashboard/system'
      preLoaderRoute: typeof DashboardSystemIndexLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/subscribe/': {
      id: '/dashboard/subscribe/'
      path: '/subscribe'
      fullPath: '/dashboard/subscribe'
      preLoaderRoute: typeof DashboardSubscribeIndexLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/product/': {
      id: '/dashboard/product/'
      path: '/product'
      fullPath: '/dashboard/product'
      preLoaderRoute: typeof DashboardProductIndexLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/payment/': {
      id: '/dashboard/payment/'
      path: '/payment'
      fullPath: '/dashboard/payment'
      preLoaderRoute: typeof DashboardPaymentIndexLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/order/': {
      id: '/dashboard/order/'
      path: '/order'
      fullPath: '/dashboard/order'
      preLoaderRoute: typeof DashboardOrderIndexLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/marketing/': {
      id: '/dashboard/marketing/'
      path: '/marketing'
      fullPath: '/dashboard/marketing'
      preLoaderRoute: typeof DashboardMarketingIndexLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/document/': {
      id: '/dashboard/document/'
      path: '/document'
      fullPath: '/dashboard/document'
      preLoaderRoute: typeof DashboardDocumentIndexLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/coupon/': {
      id: '/dashboard/coupon/'
      path: '/coupon'
      fullPath: '/dashboard/coupon'
      preLoaderRoute: typeof DashboardCouponIndexLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/auth-control/': {
      id: '/dashboard/auth-control/'
      path: '/auth-control'
      fullPath: '/dashboard/auth-control'
      preLoaderRoute: typeof DashboardAuthControlIndexLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/announcement/': {
      id: '/dashboard/announcement/'
      path: '/announcement'
      fullPath: '/dashboard/announcement'
      preLoaderRoute: typeof DashboardAnnouncementIndexLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/ads/': {
      id: '/dashboard/ads/'
      path: '/ads'
      fullPath: '/dashboard/ads'
      preLoaderRoute: typeof DashboardAdsIndexLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/log/traffic-details': {
      id: '/dashboard/log/traffic-details'
      path: '/log/traffic-details'
      fullPath: '/dashboard/log/traffic-details'
      preLoaderRoute: typeof DashboardLogTrafficDetailsLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/log/subscribe-traffic': {
      id: '/dashboard/log/subscribe-traffic'
      path: '/log/subscribe-traffic'
      fullPath: '/dashboard/log/subscribe-traffic'
      preLoaderRoute: typeof DashboardLogSubscribeTrafficLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/log/subscribe': {
      id: '/dashboard/log/subscribe'
      path: '/log/subscribe'
      fullPath: '/dashboard/log/subscribe'
      preLoaderRoute: typeof DashboardLogSubscribeLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/log/server-traffic': {
      id: '/dashboard/log/server-traffic'
      path: '/log/server-traffic'
      fullPath: '/dashboard/log/server-traffic'
      preLoaderRoute: typeof DashboardLogServerTrafficLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/log/reset-subscribe': {
      id: '/dashboard/log/reset-subscribe'
      path: '/log/reset-subscribe'
      fullPath: '/dashboard/log/reset-subscribe'
      preLoaderRoute: typeof DashboardLogResetSubscribeLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/log/register': {
      id: '/dashboard/log/register'
      path: '/log/register'
      fullPath: '/dashboard/log/register'
      preLoaderRoute: typeof DashboardLogRegisterLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/log/mobile': {
      id: '/dashboard/log/mobile'
      path: '/log/mobile'
      fullPath: '/dashboard/log/mobile'
      preLoaderRoute: typeof DashboardLogMobileLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/log/login': {
      id: '/dashboard/log/login'
      path: '/log/login'
      fullPath: '/dashboard/log/login'
      preLoaderRoute: typeof DashboardLogLoginLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/log/gift': {
      id: '/dashboard/log/gift'
      path: '/log/gift'
      fullPath: '/dashboard/log/gift'
      preLoaderRoute: typeof DashboardLogGiftLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/log/email': {
      id: '/dashboard/log/email'
      path: '/log/email'
      fullPath: '/dashboard/log/email'
      preLoaderRoute: typeof DashboardLogEmailLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/log/commission': {
      id: '/dashboard/log/commission'
      path: '/log/commission'
      fullPath: '/dashboard/log/commission'
      preLoaderRoute: typeof DashboardLogCommissionLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
    '/dashboard/log/balance': {
      id: '/dashboard/log/balance'
      path: '/log/balance'
      fullPath: '/dashboard/log/balance'
      preLoaderRoute: typeof DashboardLogBalanceLazyRouteImport
      parentRoute: typeof DashboardRouteLazyRoute
    }
  }
}

interface DashboardRouteLazyRouteChildren {
  DashboardNodesLazyRoute: typeof DashboardNodesLazyRoute
  DashboardPluginLazyRoute: typeof DashboardPluginLazyRoute
  DashboardServersLazyRoute: typeof DashboardServersLazyRoute
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
  DashboardLogBalanceLazyRoute: typeof DashboardLogBalanceLazyRoute
  DashboardLogCommissionLazyRoute: typeof DashboardLogCommissionLazyRoute
  DashboardLogEmailLazyRoute: typeof DashboardLogEmailLazyRoute
  DashboardLogGiftLazyRoute: typeof DashboardLogGiftLazyRoute
  DashboardLogLoginLazyRoute: typeof DashboardLogLoginLazyRoute
  DashboardLogMobileLazyRoute: typeof DashboardLogMobileLazyRoute
  DashboardLogRegisterLazyRoute: typeof DashboardLogRegisterLazyRoute
  DashboardLogResetSubscribeLazyRoute: typeof DashboardLogResetSubscribeLazyRoute
  DashboardLogServerTrafficLazyRoute: typeof DashboardLogServerTrafficLazyRoute
  DashboardLogSubscribeLazyRoute: typeof DashboardLogSubscribeLazyRoute
  DashboardLogSubscribeTrafficLazyRoute: typeof DashboardLogSubscribeTrafficLazyRoute
  DashboardLogTrafficDetailsLazyRoute: typeof DashboardLogTrafficDetailsLazyRoute
  DashboardAdsIndexLazyRoute: typeof DashboardAdsIndexLazyRoute
  DashboardAnnouncementIndexLazyRoute: typeof DashboardAnnouncementIndexLazyRoute
  DashboardAuthControlIndexLazyRoute: typeof DashboardAuthControlIndexLazyRoute
  DashboardCouponIndexLazyRoute: typeof DashboardCouponIndexLazyRoute
  DashboardDocumentIndexLazyRoute: typeof DashboardDocumentIndexLazyRoute
  DashboardMarketingIndexLazyRoute: typeof DashboardMarketingIndexLazyRoute
  DashboardOrderIndexLazyRoute: typeof DashboardOrderIndexLazyRoute
  DashboardPaymentIndexLazyRoute: typeof DashboardPaymentIndexLazyRoute
  DashboardProductIndexLazyRoute: typeof DashboardProductIndexLazyRoute
  DashboardSubscribeIndexLazyRoute: typeof DashboardSubscribeIndexLazyRoute
  DashboardSystemIndexLazyRoute: typeof DashboardSystemIndexLazyRoute
  DashboardTicketIndexLazyRoute: typeof DashboardTicketIndexLazyRoute
  DashboardUserIndexLazyRoute: typeof DashboardUserIndexLazyRoute
}

const DashboardRouteLazyRouteChildren: DashboardRouteLazyRouteChildren = {
  DashboardNodesLazyRoute: DashboardNodesLazyRoute,
  DashboardPluginLazyRoute: DashboardPluginLazyRoute,
  DashboardServersLazyRoute: DashboardServersLazyRoute,
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
  DashboardLogBalanceLazyRoute: DashboardLogBalanceLazyRoute,
  DashboardLogCommissionLazyRoute: DashboardLogCommissionLazyRoute,
  DashboardLogEmailLazyRoute: DashboardLogEmailLazyRoute,
  DashboardLogGiftLazyRoute: DashboardLogGiftLazyRoute,
  DashboardLogLoginLazyRoute: DashboardLogLoginLazyRoute,
  DashboardLogMobileLazyRoute: DashboardLogMobileLazyRoute,
  DashboardLogRegisterLazyRoute: DashboardLogRegisterLazyRoute,
  DashboardLogResetSubscribeLazyRoute: DashboardLogResetSubscribeLazyRoute,
  DashboardLogServerTrafficLazyRoute: DashboardLogServerTrafficLazyRoute,
  DashboardLogSubscribeLazyRoute: DashboardLogSubscribeLazyRoute,
  DashboardLogSubscribeTrafficLazyRoute: DashboardLogSubscribeTrafficLazyRoute,
  DashboardLogTrafficDetailsLazyRoute: DashboardLogTrafficDetailsLazyRoute,
  DashboardAdsIndexLazyRoute: DashboardAdsIndexLazyRoute,
  DashboardAnnouncementIndexLazyRoute: DashboardAnnouncementIndexLazyRoute,
  DashboardAuthControlIndexLazyRoute: DashboardAuthControlIndexLazyRoute,
  DashboardCouponIndexLazyRoute: DashboardCouponIndexLazyRoute,
  DashboardDocumentIndexLazyRoute: DashboardDocumentIndexLazyRoute,
  DashboardMarketingIndexLazyRoute: DashboardMarketingIndexLazyRoute,
  DashboardOrderIndexLazyRoute: DashboardOrderIndexLazyRoute,
  DashboardPaymentIndexLazyRoute: DashboardPaymentIndexLazyRoute,
  DashboardProductIndexLazyRoute: DashboardProductIndexLazyRoute,
  DashboardSubscribeIndexLazyRoute: DashboardSubscribeIndexLazyRoute,
  DashboardSystemIndexLazyRoute: DashboardSystemIndexLazyRoute,
  DashboardTicketIndexLazyRoute: DashboardTicketIndexLazyRoute,
  DashboardUserIndexLazyRoute: DashboardUserIndexLazyRoute,
}

const DashboardRouteLazyRouteWithChildren =
  DashboardRouteLazyRoute._addFileChildren(DashboardRouteLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DashboardRouteLazyRoute: DashboardRouteLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
