/**
 * Generates src/composed/icon-collections.ts: offline subsets of every iconify
 * collection referenced by the apps, so icons render without runtime requests
 * to api.iconify.design while keeping the bundle small (the full collections
 * total ~19 MB).
 *
 * Scans apps/user/src, apps/admin/src and packages/ui/src for `prefix:name`
 * string literals. Dynamic names (template literals) are covered by
 * DYNAMIC_EXTRAS below; the full flagpack collection is registered directly by
 * area-code-select.tsx (its only consumer) because country codes are unbounded.
 *
 * Run from packages/ui: bun run icons:generate
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join, resolve } from "node:path";
import type { IconifyJSON } from "@iconify/types";
import { getIcons } from "@iconify/utils";

const require = createRequire(import.meta.url);

const PREFIXES = [
  "mdi",
  "uil",
  "flat-color-icons",
  "lucide",
  "logos",
  "simple-icons",
  "tabler",
] as const;

// Icons referenced through template literals (`logos:${platform}` on the
// oauth/bind pages). Platforms come from the server's oauth method list;
// include every plausible provider that exists in the collection.
const DYNAMIC_EXTRAS: Record<string, string[]> = {
  logos: [
    "apple",
    "discord",
    "discord-icon",
    "facebook",
    "github",
    "github-icon",
    "github-octocat",
    "google",
    "google-icon",
    "line",
    "microsoft",
    "microsoft-icon",
    "telegram",
    "twitter",
    "whatsapp",
    "x",
  ],
};

const ROOT = resolve(import.meta.dir, "..");
const SCAN_DIRS = [
  resolve(ROOT, "../../apps/user/src"),
  resolve(ROOT, "../../apps/admin/src"),
  resolve(ROOT, "src"),
];
const OUT_FILE = resolve(ROOT, "src/composed/icon-collections.ts");

function* walk(dir: string): Generator<string> {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walk(path);
    } else if (/\.(ts|tsx)$/.test(entry.name)) {
      yield path;
    }
  }
}

const pattern = new RegExp(
  `(${PREFIXES.join("|")}):([a-z0-9]+(?:-[a-z0-9]+)*)`,
  "g"
);
const used = new Map<string, Set<string>>(
  PREFIXES.map((p) => [p, new Set<string>()])
);

for (const dir of SCAN_DIRS) {
  for (const file of walk(dir)) {
    const content = readFileSync(file, "utf8");
    for (const match of content.matchAll(pattern)) {
      used.get(match[1] as string)?.add(match[2] as string);
    }
  }
}

for (const [prefix, names] of Object.entries(DYNAMIC_EXTRAS)) {
  for (const name of names) {
    used.get(prefix)?.add(name);
  }
}

const collections: IconifyJSON[] = [];
for (const prefix of PREFIXES) {
  const full = JSON.parse(
    readFileSync(require.resolve(`@iconify-json/${prefix}/icons.json`), "utf8")
  ) as IconifyJSON;
  const dynamicExtras = new Set(DYNAMIC_EXTRAS[prefix] ?? []);
  const names = [...(used.get(prefix) ?? [])].filter((name) => {
    const exists = name in full.icons || name in (full.aliases ?? {});
    if (!(exists || dynamicExtras.has(name))) {
      console.warn(
        `[icons] ${prefix}:${name} not found in collection, skipped`
      );
    }
    return exists;
  });
  const subset = getIcons(full, names.sort());
  if (!subset) {
    throw new Error(`[icons] failed to build subset for ${prefix}`);
  }
  subset.lastModified = undefined;
  console.log(`[icons] ${prefix}: ${names.length} icons`);
  collections.push(subset);
}

const header = `// AUTO-GENERATED by scripts/generate-icon-collections.ts — do not edit.
// Regenerate after adding/removing icon names: cd packages/ui && bun run icons:generate
import type { IconifyJSON } from "@iconify/react";

export const collections: IconifyJSON[] = `;

writeFileSync(OUT_FILE, `${header}${JSON.stringify(collections, null, 2)};\n`);
console.log(`[icons] wrote ${OUT_FILE}`);
