/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as mainuserRouteRouteImport } from './routes/(main)/(user)/route'
import { Route as mainPurchasingOrderIndexRouteImport } from './routes/(main)/purchasing/order/index'

const mainRouteLazyRouteImport = createFileRoute('/(main)')()
const AuthIndexLazyRouteImport = createFileRoute('/auth/')()
const OauthPlatformLazyRouteImport = createFileRoute('/oauth/$platform')()
const BindPlatformLazyRouteImport = createFileRoute('/bind/$platform')()
const mainTosLazyRouteImport = createFileRoute('/(main)/tos')()
const mainPrivacyPolicyLazyRouteImport = createFileRoute(
  '/(main)/privacy-policy',
)()
const mainPaymentLazyRouteImport = createFileRoute('/(main)/payment')()
const mainPurchasingIndexLazyRouteImport = createFileRoute(
  '/(main)/purchasing/',
)()
const mainuserWalletLazyRouteImport = createFileRoute('/(main)/(user)/wallet')()
const mainuserTicketLazyRouteImport = createFileRoute('/(main)/(user)/ticket')()
const mainuserSubscribeLazyRouteImport = createFileRoute(
  '/(main)/(user)/subscribe',
)()
const mainuserProfileLazyRouteImport = createFileRoute(
  '/(main)/(user)/profile',
)()
const mainuserOrderLazyRouteImport = createFileRoute('/(main)/(user)/order')()
const mainuserDocumentLazyRouteImport = createFileRoute(
  '/(main)/(user)/document',
)()
const mainuserDashboardLazyRouteImport = createFileRoute(
  '/(main)/(user)/dashboard',
)()
const mainuserAnnouncementLazyRouteImport = createFileRoute(
  '/(main)/(user)/announcement',
)()
const mainuserAffiliateLazyRouteImport = createFileRoute(
  '/(main)/(user)/affiliate',
)()

const mainRouteLazyRoute = mainRouteLazyRouteImport
  .update({
    id: '/(main)',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(main)/route.lazy').then((d) => d.Route))
const AuthIndexLazyRoute = AuthIndexLazyRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth/index.lazy').then((d) => d.Route))
const mainIndexRoute = mainIndexRouteImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => mainRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(main)/index.lazy').then((d) => d.Route))
const OauthPlatformLazyRoute = OauthPlatformLazyRouteImport.update({
  id: '/oauth/$platform',
  path: '/oauth/$platform',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/oauth/$platform.lazy').then((d) => d.Route),
)
const BindPlatformLazyRoute = BindPlatformLazyRouteImport.update({
  id: '/bind/$platform',
  path: '/bind/$platform',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/bind/$platform.lazy').then((d) => d.Route),
)
const mainTosLazyRoute = mainTosLazyRouteImport
  .update({
    id: '/tos',
    path: '/tos',
    getParentRoute: () => mainRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(main)/tos.lazy').then((d) => d.Route))
const mainPrivacyPolicyLazyRoute = mainPrivacyPolicyLazyRouteImport
  .update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => mainRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(main)/privacy-policy.lazy').then((d) => d.Route),
  )
const mainPaymentLazyRoute = mainPaymentLazyRouteImport
  .update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => mainRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(main)/payment.lazy').then((d) => d.Route))
const mainuserRouteRoute = mainuserRouteRouteImport
  .update({
    id: '/(user)',
    getParentRoute: () => mainRouteLazyRoute,
  } as any)
  .lazy(() => import('./routes/(main)/(user)/route.lazy').then((d) => d.Route))
const mainPurchasingIndexLazyRoute = mainPurchasingIndexLazyRouteImport
  .update({
    id: '/purchasing/',
    path: '/purchasing/',
    getParentRoute: () => mainRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(main)/purchasing/index.lazy').then((d) => d.Route),
  )
const mainuserWalletLazyRoute = mainuserWalletLazyRouteImport
  .update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => mainuserRouteRoute,
  } as any)
  .lazy(() => import('./routes/(main)/(user)/wallet.lazy').then((d) => d.Route))
const mainuserTicketLazyRoute = mainuserTicketLazyRouteImport
  .update({
    id: '/ticket',
    path: '/ticket',
    getParentRoute: () => mainuserRouteRoute,
  } as any)
  .lazy(() => import('./routes/(main)/(user)/ticket.lazy').then((d) => d.Route))
const mainuserSubscribeLazyRoute = mainuserSubscribeLazyRouteImport
  .update({
    id: '/subscribe',
    path: '/subscribe',
    getParentRoute: () => mainuserRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(main)/(user)/subscribe.lazy').then((d) => d.Route),
  )
const mainuserProfileLazyRoute = mainuserProfileLazyRouteImport
  .update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => mainuserRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(main)/(user)/profile.lazy').then((d) => d.Route),
  )
const mainuserOrderLazyRoute = mainuserOrderLazyRouteImport
  .update({
    id: '/order',
    path: '/order',
    getParentRoute: () => mainuserRouteRoute,
  } as any)
  .lazy(() => import('./routes/(main)/(user)/order.lazy').then((d) => d.Route))
const mainuserDocumentLazyRoute = mainuserDocumentLazyRouteImport
  .update({
    id: '/document',
    path: '/document',
    getParentRoute: () => mainuserRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(main)/(user)/document.lazy').then((d) => d.Route),
  )
const mainuserDashboardLazyRoute = mainuserDashboardLazyRouteImport
  .update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => mainuserRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(main)/(user)/dashboard.lazy').then((d) => d.Route),
  )
const mainuserAnnouncementLazyRoute = mainuserAnnouncementLazyRouteImport
  .update({
    id: '/announcement',
    path: '/announcement',
    getParentRoute: () => mainuserRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(main)/(user)/announcement.lazy').then((d) => d.Route),
  )
const mainuserAffiliateLazyRoute = mainuserAffiliateLazyRouteImport
  .update({
    id: '/affiliate',
    path: '/affiliate',
    getParentRoute: () => mainuserRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(main)/(user)/affiliate.lazy').then((d) => d.Route),
  )
const mainPurchasingOrderIndexRoute = mainPurchasingOrderIndexRouteImport
  .update({
    id: '/purchasing/order/',
    path: '/purchasing/order/',
    getParentRoute: () => mainRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(main)/purchasing/order/index.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof mainIndexRoute
  '/payment': typeof mainPaymentLazyRoute
  '/privacy-policy': typeof mainPrivacyPolicyLazyRoute
  '/tos': typeof mainTosLazyRoute
  '/bind/$platform': typeof BindPlatformLazyRoute
  '/oauth/$platform': typeof OauthPlatformLazyRoute
  '/auth': typeof AuthIndexLazyRoute
  '/affiliate': typeof mainuserAffiliateLazyRoute
  '/announcement': typeof mainuserAnnouncementLazyRoute
  '/dashboard': typeof mainuserDashboardLazyRoute
  '/document': typeof mainuserDocumentLazyRoute
  '/order': typeof mainuserOrderLazyRoute
  '/profile': typeof mainuserProfileLazyRoute
  '/subscribe': typeof mainuserSubscribeLazyRoute
  '/ticket': typeof mainuserTicketLazyRoute
  '/wallet': typeof mainuserWalletLazyRoute
  '/purchasing': typeof mainPurchasingIndexLazyRoute
  '/purchasing/order': typeof mainPurchasingOrderIndexRoute
}
export interface FileRoutesByTo {
  '/payment': typeof mainPaymentLazyRoute
  '/privacy-policy': typeof mainPrivacyPolicyLazyRoute
  '/tos': typeof mainTosLazyRoute
  '/bind/$platform': typeof BindPlatformLazyRoute
  '/oauth/$platform': typeof OauthPlatformLazyRoute
  '/': typeof mainIndexRoute
  '/auth': typeof AuthIndexLazyRoute
  '/affiliate': typeof mainuserAffiliateLazyRoute
  '/announcement': typeof mainuserAnnouncementLazyRoute
  '/dashboard': typeof mainuserDashboardLazyRoute
  '/document': typeof mainuserDocumentLazyRoute
  '/order': typeof mainuserOrderLazyRoute
  '/profile': typeof mainuserProfileLazyRoute
  '/subscribe': typeof mainuserSubscribeLazyRoute
  '/ticket': typeof mainuserTicketLazyRoute
  '/wallet': typeof mainuserWalletLazyRoute
  '/purchasing': typeof mainPurchasingIndexLazyRoute
  '/purchasing/order': typeof mainPurchasingOrderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteLazyRouteWithChildren
  '/(main)/(user)': typeof mainuserRouteRouteWithChildren
  '/(main)/payment': typeof mainPaymentLazyRoute
  '/(main)/privacy-policy': typeof mainPrivacyPolicyLazyRoute
  '/(main)/tos': typeof mainTosLazyRoute
  '/bind/$platform': typeof BindPlatformLazyRoute
  '/oauth/$platform': typeof OauthPlatformLazyRoute
  '/(main)/': typeof mainIndexRoute
  '/auth/': typeof AuthIndexLazyRoute
  '/(main)/(user)/affiliate': typeof mainuserAffiliateLazyRoute
  '/(main)/(user)/announcement': typeof mainuserAnnouncementLazyRoute
  '/(main)/(user)/dashboard': typeof mainuserDashboardLazyRoute
  '/(main)/(user)/document': typeof mainuserDocumentLazyRoute
  '/(main)/(user)/order': typeof mainuserOrderLazyRoute
  '/(main)/(user)/profile': typeof mainuserProfileLazyRoute
  '/(main)/(user)/subscribe': typeof mainuserSubscribeLazyRoute
  '/(main)/(user)/ticket': typeof mainuserTicketLazyRoute
  '/(main)/(user)/wallet': typeof mainuserWalletLazyRoute
  '/(main)/purchasing/': typeof mainPurchasingIndexLazyRoute
  '/(main)/purchasing/order/': typeof mainPurchasingOrderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/payment'
    | '/privacy-policy'
    | '/tos'
    | '/bind/$platform'
    | '/oauth/$platform'
    | '/auth'
    | '/affiliate'
    | '/announcement'
    | '/dashboard'
    | '/document'
    | '/order'
    | '/profile'
    | '/subscribe'
    | '/ticket'
    | '/wallet'
    | '/purchasing'
    | '/purchasing/order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/payment'
    | '/privacy-policy'
    | '/tos'
    | '/bind/$platform'
    | '/oauth/$platform'
    | '/'
    | '/auth'
    | '/affiliate'
    | '/announcement'
    | '/dashboard'
    | '/document'
    | '/order'
    | '/profile'
    | '/subscribe'
    | '/ticket'
    | '/wallet'
    | '/purchasing'
    | '/purchasing/order'
  id:
    | '__root__'
    | '/(main)'
    | '/(main)/(user)'
    | '/(main)/payment'
    | '/(main)/privacy-policy'
    | '/(main)/tos'
    | '/bind/$platform'
    | '/oauth/$platform'
    | '/(main)/'
    | '/auth/'
    | '/(main)/(user)/affiliate'
    | '/(main)/(user)/announcement'
    | '/(main)/(user)/dashboard'
    | '/(main)/(user)/document'
    | '/(main)/(user)/order'
    | '/(main)/(user)/profile'
    | '/(main)/(user)/subscribe'
    | '/(main)/(user)/ticket'
    | '/(main)/(user)/wallet'
    | '/(main)/purchasing/'
    | '/(main)/purchasing/order/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteLazyRoute: typeof mainRouteLazyRouteWithChildren
  BindPlatformLazyRoute: typeof BindPlatformLazyRoute
  OauthPlatformLazyRoute: typeof OauthPlatformLazyRoute
  AuthIndexLazyRoute: typeof AuthIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteLazyRoute
    }
    '/oauth/$platform': {
      id: '/oauth/$platform'
      path: '/oauth/$platform'
      fullPath: '/oauth/$platform'
      preLoaderRoute: typeof OauthPlatformLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bind/$platform': {
      id: '/bind/$platform'
      path: '/bind/$platform'
      fullPath: '/bind/$platform'
      preLoaderRoute: typeof BindPlatformLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/tos': {
      id: '/(main)/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof mainTosLazyRouteImport
      parentRoute: typeof mainRouteLazyRoute
    }
    '/(main)/privacy-policy': {
      id: '/(main)/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof mainPrivacyPolicyLazyRouteImport
      parentRoute: typeof mainRouteLazyRoute
    }
    '/(main)/payment': {
      id: '/(main)/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof mainPaymentLazyRouteImport
      parentRoute: typeof mainRouteLazyRoute
    }
    '/(main)/(user)': {
      id: '/(main)/(user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainuserRouteRouteImport
      parentRoute: typeof mainRouteLazyRoute
    }
    '/(main)/purchasing/': {
      id: '/(main)/purchasing/'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof mainPurchasingIndexLazyRouteImport
      parentRoute: typeof mainRouteLazyRoute
    }
    '/(main)/(user)/wallet': {
      id: '/(main)/(user)/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof mainuserWalletLazyRouteImport
      parentRoute: typeof mainuserRouteRoute
    }
    '/(main)/(user)/ticket': {
      id: '/(main)/(user)/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof mainuserTicketLazyRouteImport
      parentRoute: typeof mainuserRouteRoute
    }
    '/(main)/(user)/subscribe': {
      id: '/(main)/(user)/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof mainuserSubscribeLazyRouteImport
      parentRoute: typeof mainuserRouteRoute
    }
    '/(main)/(user)/profile': {
      id: '/(main)/(user)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof mainuserProfileLazyRouteImport
      parentRoute: typeof mainuserRouteRoute
    }
    '/(main)/(user)/order': {
      id: '/(main)/(user)/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof mainuserOrderLazyRouteImport
      parentRoute: typeof mainuserRouteRoute
    }
    '/(main)/(user)/document': {
      id: '/(main)/(user)/document'
      path: '/document'
      fullPath: '/document'
      preLoaderRoute: typeof mainuserDocumentLazyRouteImport
      parentRoute: typeof mainuserRouteRoute
    }
    '/(main)/(user)/dashboard': {
      id: '/(main)/(user)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainuserDashboardLazyRouteImport
      parentRoute: typeof mainuserRouteRoute
    }
    '/(main)/(user)/announcement': {
      id: '/(main)/(user)/announcement'
      path: '/announcement'
      fullPath: '/announcement'
      preLoaderRoute: typeof mainuserAnnouncementLazyRouteImport
      parentRoute: typeof mainuserRouteRoute
    }
    '/(main)/(user)/affiliate': {
      id: '/(main)/(user)/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof mainuserAffiliateLazyRouteImport
      parentRoute: typeof mainuserRouteRoute
    }
    '/(main)/purchasing/order/': {
      id: '/(main)/purchasing/order/'
      path: '/purchasing/order'
      fullPath: '/purchasing/order'
      preLoaderRoute: typeof mainPurchasingOrderIndexRouteImport
      parentRoute: typeof mainRouteLazyRoute
    }
  }
}

interface mainuserRouteRouteChildren {
  mainuserAffiliateLazyRoute: typeof mainuserAffiliateLazyRoute
  mainuserAnnouncementLazyRoute: typeof mainuserAnnouncementLazyRoute
  mainuserDashboardLazyRoute: typeof mainuserDashboardLazyRoute
  mainuserDocumentLazyRoute: typeof mainuserDocumentLazyRoute
  mainuserOrderLazyRoute: typeof mainuserOrderLazyRoute
  mainuserProfileLazyRoute: typeof mainuserProfileLazyRoute
  mainuserSubscribeLazyRoute: typeof mainuserSubscribeLazyRoute
  mainuserTicketLazyRoute: typeof mainuserTicketLazyRoute
  mainuserWalletLazyRoute: typeof mainuserWalletLazyRoute
}

const mainuserRouteRouteChildren: mainuserRouteRouteChildren = {
  mainuserAffiliateLazyRoute: mainuserAffiliateLazyRoute,
  mainuserAnnouncementLazyRoute: mainuserAnnouncementLazyRoute,
  mainuserDashboardLazyRoute: mainuserDashboardLazyRoute,
  mainuserDocumentLazyRoute: mainuserDocumentLazyRoute,
  mainuserOrderLazyRoute: mainuserOrderLazyRoute,
  mainuserProfileLazyRoute: mainuserProfileLazyRoute,
  mainuserSubscribeLazyRoute: mainuserSubscribeLazyRoute,
  mainuserTicketLazyRoute: mainuserTicketLazyRoute,
  mainuserWalletLazyRoute: mainuserWalletLazyRoute,
}

const mainuserRouteRouteWithChildren = mainuserRouteRoute._addFileChildren(
  mainuserRouteRouteChildren,
)

interface mainRouteLazyRouteChildren {
  mainuserRouteRoute: typeof mainuserRouteRouteWithChildren
  mainPaymentLazyRoute: typeof mainPaymentLazyRoute
  mainPrivacyPolicyLazyRoute: typeof mainPrivacyPolicyLazyRoute
  mainTosLazyRoute: typeof mainTosLazyRoute
  mainIndexRoute: typeof mainIndexRoute
  mainPurchasingIndexLazyRoute: typeof mainPurchasingIndexLazyRoute
  mainPurchasingOrderIndexRoute: typeof mainPurchasingOrderIndexRoute
}

const mainRouteLazyRouteChildren: mainRouteLazyRouteChildren = {
  mainuserRouteRoute: mainuserRouteRouteWithChildren,
  mainPaymentLazyRoute: mainPaymentLazyRoute,
  mainPrivacyPolicyLazyRoute: mainPrivacyPolicyLazyRoute,
  mainTosLazyRoute: mainTosLazyRoute,
  mainIndexRoute: mainIndexRoute,
  mainPurchasingIndexLazyRoute: mainPurchasingIndexLazyRoute,
  mainPurchasingOrderIndexRoute: mainPurchasingOrderIndexRoute,
}

const mainRouteLazyRouteWithChildren = mainRouteLazyRoute._addFileChildren(
  mainRouteLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteLazyRoute: mainRouteLazyRouteWithChildren,
  BindPlatformLazyRoute: BindPlatformLazyRoute,
  OauthPlatformLazyRoute: OauthPlatformLazyRoute,
  AuthIndexLazyRoute: AuthIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
